
#define REG_MOUSE_STATUS (MMIO_BASE + 0x38)

#define MOUSE_READY_MASK   0x1u
#define MOUSE_LEFT_MASK    0x2u
#define MOUSE_RIGHT_MASK   0x4u
#define MOUSE_CHANGED_MASK 0x8u
#define MOUSE_COORD_MASK   0x3FFu




